In [32]:
import numpy as np

In [33]:
position1 = np.array([[0,1],[2,3]])
position2 = np.array([[3,4],[5,6],[7,6]])
position_1_index = np.linspace(0,1,2)
position_2_index = np.linspace(0,2,3)

In [34]:
position_1_index

array([0., 1.])

In [35]:
xx,yy = np.meshgrid(position_1_index,position_2_index)

In [36]:
xx,yy

(array([[0., 1.],
        [0., 1.],
        [0., 1.]]),
 array([[0., 0.],
        [1., 1.],
        [2., 2.]]))

In [40]:
rij = []
for i in range(np.shape(xx)[0]) : 
    for j in range(np.shape(xx)[1]) :
        print(position1[int(xx[i][j])]-position2[int(yy[i][j])])
        rij.append(position1[int(xx[i][j])]-position2[int(yy[i][j])])

[-3 -3]
[-1 -1]
[-5 -5]
[-3 -3]
[-7 -5]
[-5 -3]


In [41]:
print(rij)

[array([-3, -3]), array([-1, -1]), array([-5, -5]), array([-3, -3]), array([-7, -5]), array([-5, -3])]
